export const siteCopy = {
  en: {
    title: 'Custom AI Agent Development — Rami Halabi',
    description: 'Custom AI agents and tool services built around your company’s workflows. Explore bilingual demos for support, document tailoring and governed software development.',
    nav: ['Services', 'Demos', 'Approach', 'Let’s talk'], skip: 'Skip to content', home: 'Home', language: 'Language',
    eyebrow: 'Custom AI agents & tool services', hero: 'Built for your work.', heroMuted: 'Connected to your systems.',
    intro: 'I’m Rami Halabi. I design and build agents that use company knowledge, call useful tools and move a task through a clear workflow—with people deciding what matters.',
    discuss: 'Discuss your project', explore: 'Explore the demos', footnote: 'Start with one useful workflow. Build the right system around it.',
    diagram: 'From request to reviewed result', architecture: 'Illustrative architecture. Sources, permissions and approval rules are defined for each use case.',
    nodes: [['A request comes in', 'A question, a document, a development task'], ['Your custom agent', 'Find context. Coordinate the next step.'], ['A focused tool does its job', 'Search, tailor a document, call an API'], ['Review and move forward', 'A supported answer, a draft, an approved action']],
    pills: ['Company knowledge', 'APIs & tools'], strip: ['Knowledge & retrieval', 'Tool & API integration', 'Workflow orchestration', 'Human oversight'],
    servicesLabel: '01 / Services', servicesTitle: 'Start with the work that needs doing.', servicesIntro: 'Bring a process that is repetitive, hard to navigate or spread across systems. We’ll define a useful role for an agent and the boundaries it needs.',
    services: [
      ['01 — SUPPORT & KNOWLEDGE', 'Help people find a useful answer.', 'Assistants that work with approved information and hand over when a question needs a person.', ['Knowledge retrieval and source references', 'Support triage and contextual handover', 'Voice and dictation workflows to scope']],
      ['02 — TOOLS & DOCUMENTS', 'Give an agent the right tools.', 'Focused services that connect an agent to your APIs, data and document workflows.', ['Document tailoring from approved material', 'Tool interfaces and system integrations', 'Drafts routed through human review']],
      ['03 — ENGINEERING', 'Coordinate work with clear boundaries.', 'Agent architecture and software-development workflows built around explicit permissions and review.', ['Development agents and task coordination', 'Agent and multi-agent orchestration', 'Architecture review and consulting']],
    ],
    servicesNote: 'These are services to scope for your company. The presentations below explain the ideas and the workflows they could support.',
    demosLabel: '02 / Demos', demosTitle: 'See the workflow. Understand the system.', demosIntro: 'Three guided presentations, available in English and Swedish. Each explains a different part of an agent system and clearly states what it demonstrates.', watch: 'Explore the walkthrough', gallery: 'All demos',
    distinctionTitle: 'An agent and a tool have different jobs.', distinctionIntro: 'A useful system can combine both. The agent coordinates the task; a tool performs a focused operation. Your workflow defines when people review and approve the result.',
    distinctions: [['Soher Agent coordinates development', 'Turn a request into a plan, divide the work and bring the result back for your team to review.'], ['Soher Docs tailors documents', 'A tool-service concept an agent can call. CVs are the current example; contracts and other documents are future scope.'], ['Hektor illustrates customer support', 'A concept for answers from approved knowledge, human handover and staff documentation.']],
    approachLabel: '03 / Working together', approachTitle: 'A practical route from problem to system.', approachIntro: 'I work from the process outward: what needs to happen, what information is available, which tools are involved and who makes the decisions.',
    process: [['Understand the work', 'Map a real task, its users, the inputs and the result you want.'], ['Define the boundaries', 'Agree access, tool actions, review points and what success means.'], ['Build a focused version', 'Connect the necessary pieces and make the workflow inspectable.'], ['Validate and refine', 'Check realistic examples, handle exceptions and agree the next scope.']],
    faqTitle: 'Before we start.', faqs: [
      ['Are these live products?', 'These are guided presentations of agent and tool-service concepts. They explain the intended workflows; none of the public demos connects to your company systems.'],
      ['Is Soher Docs only for CVs?', 'CV tailoring is the current example of a document tool an agent can use. Other document types, including contracts, are a future direction that needs its own sources, rules and expert review.'],
      ['Can this work with our existing tools?', 'Integration starts with your systems’ interfaces, permissions and data access. We can scope API connections or a focused tool service around your existing workflow.'],
      ['What should I bring to a first conversation?', 'One recurring task, the tools involved, the source material available and a description of a good result. A high-level overview is enough to start.'],
    ],
    contactLabel: '04 / Start a conversation', contactTitle: 'What should your agent help you do?', contactText: 'Tell me about the work, the systems involved and where your team gets stuck. We can turn that into a concrete scope.', contactButton: 'Contact Rami on LinkedIn', contactNote: 'Opens LinkedIn. No enquiry is sent from this website.', briefLabel: 'A useful first message', briefTitle: 'Start with the task.', brief: ['What should happen?', 'Which tools or documents are involved?', 'What needs human approval?', 'What would a good result look like?'], briefNote: 'Share a high-level outline to start; no sensitive documents are needed.',
    footer: 'Custom AI agents. Clear workflows. Practical engineering.',
    demoLabel: 'Guided demonstration', view: 'Watch the presentation', transcript: 'Read the slides & transcript', download: 'Download video', silent: 'Silent presentation', chapter: 'Chapter', chapters: 'Presentation chapters', fallback: 'Your browser cannot play this recording.', openVideo: 'Open the MP4', boundaries: 'What this demonstrates', fitTitle: 'Where this could fit', nextTitle: 'Build around your workflow.', nextButton: 'Discuss a similar project', otherDemos: 'Explore another workflow',
    archiveTitle: 'Inspect the original material', archiveNote: 'Original evidence retains its source language and historical context. The presentation above is available in both languages.',
    archiveDocs: 'Original seven-step CV visualization (English)', archiveHektor: 'Original 14-slide Hektor recording (Swedish)',
    slide: 'Slide', back: 'Back to the demo', transcriptIntro: 'Read the full presentation at your own pace. Every slide and its text are included below.', previous: 'Previous', nextSlide: 'Next', readText: 'Slide text', recordingDetails: 'Recording provenance',
    workTitle: 'Agent demos & workflows — Rami Halabi', workHeading: 'Three ways to explore agent systems.',
  },
  sv: {
    title: 'Skräddarsydda AI-agenter — Rami Halabi',
    description: 'Skräddarsydda AI-agenter och verktygstjänster utifrån företagets arbetsflöden. Se tvåspråkiga genomgångar av support, dokumentanpassning och styrd mjukvaruutveckling.',
    nav: ['Tjänster', 'Demor', 'Arbetssätt', 'Prata med mig'], skip: 'Hoppa till innehåll', home: 'Hem', language: 'Språk',
    eyebrow: 'Skräddarsydda AI-agenter och verktygstjänster', hero: 'Byggt för ert arbete.', heroMuted: 'Kopplat till era system.',
    intro: 'Jag heter Rami Halabi. Jag designar och bygger agenter som använder företagets kunskap, anropar användbara verktyg och driver en uppgift genom ett tydligt flöde—med människor som fattar de viktiga besluten.',
    discuss: 'Diskutera ert projekt', explore: 'Utforska genomgångarna', footnote: 'Börja med ett användbart flöde. Bygg rätt system runt det.',
    diagram: 'Från begäran till granskat resultat', architecture: 'Illustrativ arkitektur. Källor, behörigheter och regler för godkännande definieras för varje användningsfall.',
    nodes: [['En begäran kommer in', 'En fråga, ett dokument, en utvecklingsuppgift'], ['Er skräddarsydda agent', 'Hitta sammanhang. Samordna nästa steg.'], ['Ett avgränsat verktyg gör sitt jobb', 'Sök, anpassa ett dokument, anropa ett API'], ['Granska och gå vidare', 'Ett belagt svar, ett utkast, en godkänd åtgärd']],
    pills: ['Företagets kunskap', 'API:er och verktyg'], strip: ['Kunskap och sökning', 'Verktyg och API-integration', 'Samordnade arbetsflöden', 'Mänsklig kontroll'],
    servicesLabel: '01 / Tjänster', servicesTitle: 'Börja med arbetet som behöver göras.', servicesIntro: 'Ta med en process som är repetitiv, svår att överblicka eller utspridd över flera system. Vi definierar en användbar roll för en agent och de gränser den behöver.',
    services: [
      ['01 — SUPPORT OCH KUNSKAP', 'Hjälp människor hitta användbara svar.', 'Assistenter som arbetar med godkänd information och lämnar över när en fråga kräver en människa.', ['Kunskapssökning och källhänvisningar', 'Supporttriage och överlämning med sammanhang', 'Röst- och dikteringsflöden att avgränsa']],
      ['02 — VERKTYG OCH DOKUMENT', 'Ge agenten rätt verktyg.', 'Avgränsade tjänster som kopplar en agent till era API:er, data och dokumentflöden.', ['Dokumentanpassning från godkänt underlag', 'Verktygsgränssnitt och systemintegrationer', 'Utkast som går genom mänsklig granskning']],
      ['03 — UTVECKLING', 'Samordna arbetet med tydliga ramar.', 'Agentarkitektur och flöden för mjukvaruutveckling utifrån uttryckliga behörigheter och granskning.', ['Utvecklingsagenter och uppgiftssamordning', 'Samordning av agenter och multiagentsystem', 'Arkitekturgranskning och rådgivning']],
    ],
    servicesNote: 'Detta är tjänster att avgränsa för ert företag. Presentationerna nedan förklarar idéerna och de arbetsflöden de skulle kunna stödja.',
    demosLabel: '02 / Demor', demosTitle: 'Se arbetsflödet. Förstå systemet.', demosIntro: 'Tre vägledda presentationer på svenska och engelska. Varje presentation förklarar en del av ett agentsystem och anger tydligt vad den visar.', watch: 'Utforska genomgången', gallery: 'Alla demor',
    distinctionTitle: 'En agent och ett verktyg har olika uppgifter.', distinctionIntro: 'Ett användbart system kan kombinera båda. Agenten samordnar uppgiften, medan ett verktyg utför en avgränsad operation. Ert arbetsflöde avgör när människor granskar och godkänner resultatet.',
    distinctions: [['Soher Agent samordnar utveckling', 'Gör en begäran till en plan, dela upp arbetet och lämna resultatet till ert team för granskning.'], ['Soher Docs anpassar dokument', 'Ett koncept för en verktygstjänst som en agent kan anropa. CV är det aktuella exemplet; avtal och andra dokument är framtida omfattning.'], ['Hektor illustrerar kundsupport', 'Ett koncept för svar från godkänd kunskap, mänsklig överlämning och personalens dokumentation.']],
    approachLabel: '03 / Arbeta tillsammans', approachTitle: 'En praktisk väg från problem till system.', approachIntro: 'Jag börjar i processen: vad som behöver hända, vilken information som finns, vilka verktyg som används och vem som fattar besluten.',
    process: [['Förstå arbetet', 'Kartlägg en verklig uppgift, användarna, underlaget och det önskade resultatet.'], ['Definiera gränserna', 'Bestäm åtkomst, verktygsåtgärder, granskningspunkter och kriterier för ett bra resultat.'], ['Bygg en avgränsad version', 'Koppla ihop delarna som behövs och gör flödet möjligt att granska.'], ['Validera och förbättra', 'Kontrollera realistiska exempel, hantera undantag och bestäm nästa omfattning.']],
    faqTitle: 'Innan vi börjar.', faqs: [
      ['Är detta fungerande produkter?', 'Detta är vägledda presentationer av koncept för agenter och verktygstjänster. De förklarar de tänkta arbetsflödena; ingen publik demo ansluter till era företagssystem.'],
      ['Är Soher Docs bara till för CV:n?', 'CV-anpassning är det aktuella exemplet på ett dokumentverktyg som en agent kan använda. Andra dokumenttyper, inklusive avtal, är en framtida inriktning som behöver egna källor, regler och sakkunnig granskning.'],
      ['Kan det fungera med våra befintliga verktyg?', 'Integration börjar med era systems gränssnitt, behörigheter och dataåtkomst. Vi kan avgränsa API-kopplingar eller en verktygstjänst utifrån ert befintliga arbetsflöde.'],
      ['Vad behöver jag till ett första samtal?', 'En återkommande uppgift, verktygen som används, tillgängligt underlag och en beskrivning av ett bra resultat. En övergripande bild räcker för att börja.'],
    ],
    contactLabel: '04 / Starta ett samtal', contactTitle: 'Vad ska er agent hjälpa er att göra?', contactText: 'Berätta om arbetet, systemen som används och var ert team fastnar. Vi kan göra det till en konkret omfattning.', contactButton: 'Kontakta Rami på LinkedIn', contactNote: 'Öppnar LinkedIn. Ingen förfrågan skickas från denna webbplats.', briefLabel: 'Ett användbart första meddelande', briefTitle: 'Börja med uppgiften.', brief: ['Vad ska hända?', 'Vilka verktyg eller dokument används?', 'Vad behöver mänskligt godkännande?', 'Hur ser ett bra resultat ut?'], briefNote: 'Börja med en övergripande beskrivning; inga känsliga dokument behövs.',
    footer: 'Skräddarsydda AI-agenter. Tydliga flöden. Praktisk utveckling.',
    demoLabel: 'Vägledd demonstration', view: 'Se presentationen', transcript: 'Läs bilderna och genomgången', download: 'Ladda ner video', silent: 'Presentation utan ljud', chapter: 'Avsnitt', chapters: 'Presentationens avsnitt', fallback: 'Din webbläsare kan inte spela inspelningen.', openVideo: 'Öppna MP4-filen', boundaries: 'Vad detta visar', fitTitle: 'Var detta kan passa', nextTitle: 'Bygg utifrån ert arbetsflöde.', nextButton: 'Diskutera ett liknande projekt', otherDemos: 'Utforska ett annat arbetsflöde',
    archiveTitle: 'Granska originalmaterialet', archiveNote: 'Originalunderlaget behåller sitt källspråk och historiska sammanhang. Presentationen ovan finns på båda språken.',
    archiveDocs: 'Ursprunglig CV-visualisering i sju steg (engelska)', archiveHektor: 'Ursprunglig Hektor-inspelning med 14 bilder (svenska)',
    slide: 'Bild', back: 'Tillbaka till demon', transcriptIntro: 'Läs hela presentationen i din egen takt. Varje bild och dess text finns nedan.', previous: 'Föregående', nextSlide: 'Nästa', readText: 'Bildtext', recordingDetails: 'Underlag för inspelningen',
    workTitle: 'Agentdemor och arbetsflöden — Rami Halabi', workHeading: 'Tre sätt att utforska agentsystem.',
  },
}
